[package]
name = "game"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
editor = []

[dependencies]
wasm-bindgen = "0.2.92"
console_error_panic_hook = "0.1"
unicode-segmentation = "1.12.0"
fnv = "1.0.7"
parking_lot = "0.12.3"
